version: '3.8'
services:

  netmatch-web:
    build:
      context: ./
      target: netmatch-web
    ports:
      - 4200:4200
    volumes:
      - .:/app
    depends_on:
      - netmatch-api

  netmatch-api:
    build: 
      context: ./
      target: netmatch-api
    environment:
      - PORT=3333
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - netmatch-db

  netmatch-db:
    image: mongo
    container_name: netmatch-db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db.js:/docker-entrypoint-initdb.d/db.js:rw
      - ./mongo-volume:/data/db
      - ./.env:/.env
    ports:
      - "27017:27017"
