version: '3.8'
services:

  netmatch-web:
    build:
      context: ./
      target: netmatch-web
    ports:
      - 4200:4200
    volumes:
      - .:/app
    depends_on:
      - netmatch-api

  netmatch-api:
    build: 
      context: ./
      target: netmatch-api
    environment:
      - PORT=3333
    ports:
      - 3333:3333
    volumes:
      - .:/app
