version: '3.8'
services:
  netmatch-web-service:
    build:
      context: ./
      target: netmatch-web
    ports:
      - 4200:4200
    volumes:
      - .:/app

  netmatch-api-service:
    build: 
      context: ./
      target: netmatch-api
    ports:
      - 3333:3333
    volumes:
      - .:/app
